"use server";

import { revalidatePath } from "next/cache";
import { Resend } from "resend";
import { gogaAdmin } from "@/app/lib/supabase/goga";
import { requireSession } from "./require-auth";
import { logAdminEvent } from "./admin-events";

function randomToken(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(18));
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]!);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/** Default English contract body — autogenerated from a booking row. */
function defaultBodyEn(args: {
  clientName: string;
  shootDate: string;
  location: string | null;
  packageName: string;
  total: string;
  deposit: string;
}): string {
  return `Photography Service Agreement

This agreement is between GOGA Photography ("the Studio") and ${args.clientName} ("the Client") for photography services on ${args.shootDate}${args.location ? ` at ${args.location}` : ""}.

PACKAGE — ${args.packageName}
TOTAL — ${args.total}
DEPOSIT — ${args.deposit} (non-refundable, secures the date)

DELIVERY
Edited photographs will be delivered via a private online gallery within 8 weeks of the shoot. The Client receives a personal-use license; commercial use requires a separate written license.

CANCELLATION
The deposit is non-refundable. If the Client cancels more than 60 days before the shoot, the Studio will credit it toward a future booking within 12 months. If the Studio cannot perform due to illness or force majeure, the deposit will be refunded in full and reasonable effort made to refer a comparable photographer.

COPYRIGHT
The Studio retains copyright of all images. The Client may share images on personal social media with credit. The Studio may use images for its portfolio, marketing, and submissions to publications.

By signing below, both parties agree to these terms.`;
}

function fmtMoney(cents: number, currency: string): string {
  try {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(cents / 100);
  } catch {
    return `${(cents / 100).toFixed(0)} ${currency}`;
  }
}

/**
 * Ensure a contract exists for this booking and return it. Idempotent —
 * if a non-void contract already exists we return that one instead of
 * making a duplicate.
 */
export async function ensureContractForBooking(
  bookingId: string,
): Promise<{ id: string; token: string; created: boolean }> {
  await requireSession();
  const sb = gogaAdmin();

  const { data: existing } = await sb
    .from("contracts")
    .select("id, token")
    .eq("booking_id", bookingId)
    .neq("status", "void")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (existing) return { ...existing, created: false };

  const { data: booking } = await sb
    .from("bookings")
    .select(
      `id, shoot_date, location, subtotal_cents, deposit_cents, currency,
       client_name, client_email, packages(name_en)`,
    )
    .eq("id", bookingId)
    .single();
  if (!booking) throw new Error("booking_not_found");

  const total = fmtMoney(booking.subtotal_cents, booking.currency);
  const deposit = fmtMoney(booking.deposit_cents, booking.currency);
  const body_en = defaultBodyEn({
    clientName: booking.client_name ?? "(client)",
    shootDate: booking.shoot_date,
    location: booking.location,
    packageName: booking.packages?.name_en ?? "Photography session",
    total,
    deposit,
  });

  const token = randomToken();
  const { data, error } = await sb
    .from("contracts")
    .insert({
      booking_id: bookingId,
      token,
      body_en,
      signer_name: booking.client_name,
      signer_email: booking.client_email,
      status: "draft",
    })
    .select("id, token")
    .single();
  if (error || !data) throw new Error(error?.message ?? "insert_failed");
  await logAdminEvent("contract.created", {
    entityType: "contract",
    entityId: data.id,
    payload: { bookingId },
  });

  revalidatePath(`/app/bookings/${bookingId}`);
  revalidatePath("/app/contracts");
  return { id: data.id, token: data.token, created: true };
}

export async function updateContractBody(
  id: string,
  patch: { body_en?: string | null; body_ka?: string | null },
): Promise<void> {
  await requireSession();
  const sb = gogaAdmin();
  const { data: c } = await sb
    .from("contracts")
    .select("status")
    .eq("id", id)
    .single();
  if (!c || c.status === "signed") {
    throw new Error("cannot_edit_signed");
  }
  await sb.from("contracts").update(patch).eq("id", id);
  revalidatePath(`/app/contracts/${id}`);
}

export async function sendContract(id: string): Promise<{ ok: boolean }> {
  await requireSession();
  const sb = gogaAdmin();
  const { data: c } = await sb
    .from("contracts")
    .select(
      `id, token, status, signer_email, signer_name, body_en,
       bookings(shoot_date, packages(name_en))`,
    )
    .eq("id", id)
    .single();
  if (!c) throw new Error("not_found");
  if (c.status === "signed") throw new Error("already_signed");
  if (!c.signer_email) throw new Error("no_signer_email");
  if (!c.body_en?.trim()) throw new Error("empty_body");

  const origin =
    process.env["NEXT_PUBLIC_SITE_URL"] ??
    (process.env["VERCEL_URL"]
      ? `https://${process.env["VERCEL_URL"]}`
      : "http://localhost:3030");
  const url = `${origin}/sign/${c.token}`;

  const key = process.env["RESEND_API_KEY"];
  if (key) {
    const resend = new Resend(key);
    const from =
      process.env["CONTACT_FROM_ADDRESS"] ?? "no-reply@goga.photography";
    const pkg = c.bookings?.packages?.name_en ?? "your photography session";
    await resend.emails.send({
      from: `GOGA Photography <${from}>`,
      to: c.signer_email,
      subject: `Contract for ${pkg}`,
      text: `Hi${c.signer_name ? " " + c.signer_name : ""},\n\nPlease review and sign the contract for ${pkg}${c.bookings?.shoot_date ? ` on ${c.bookings.shoot_date}` : ""}:\n\n${url}\n\nThanks,\nGoga`,
    });
  }

  await sb
    .from("contracts")
    .update({ status: "sent", sent_at: new Date().toISOString() })
    .eq("id", id);
  await logAdminEvent("contract.sent", {
    entityType: "contract",
    entityId: id,
    payload: { to: c.signer_email, emailed: !!key },
  });

  revalidatePath(`/app/contracts/${id}`);
  revalidatePath("/app/contracts");
  return { ok: true };
}

export async function voidContract(id: string): Promise<void> {
  await requireSession();
  await gogaAdmin().from("contracts").update({ status: "void" }).eq("id", id);
  await logAdminEvent("contract.voided", {
    entityType: "contract",
    entityId: id,
  });
  revalidatePath(`/app/contracts/${id}`);
  revalidatePath("/app/contracts");
}
