/**
 * One-shot migration: travelpl_tm (mariadb) → travelplace-bf (Supabase Postgres).
 * Tables migrated in dependency order. Idempotent: truncates the target before insert.
 *
 * Usage:
 *   MARIA_URL='mysql://root:rootpw@127.0.0.1:3306/travelpl_tm' \
 *   SUPABASE_DB_URL='postgresql://...' \
 *   npx tsx scripts/migrate-from-mariadb.ts
 */
import mysql from "mysql2/promise";
import { Client as PgClient } from "pg";

const MARIA_URL = process.env.MARIA_URL;
const SUPABASE_DB_URL = process.env.SUPABASE_DB_URL;
if (!MARIA_URL || !SUPABASE_DB_URL) {
  console.error("Set MARIA_URL and SUPABASE_DB_URL env vars.");
  process.exit(1);
}

// Order matters — parents before children.
const TABLES = [
  { name: "role", cols: ["id", "name"] },
  { name: "c_admin_position", cols: ["id", "name"] },
  { name: "setting", cols: ["id", "key", "value"] },
  { name: "c_juridical_form", cols: ["id", "name"] },
  { name: "c_hotel_group", cols: ["id", "name"] },
  { name: "cc1_country", cols: ["id", "name", "code"] },
  { name: "cc1_region", cols: ["id", "cc1_country_id", "name"] },
  { name: "cc1_city", cols: ["id", "cc1_region_id", "name"] },
  {
    name: "administration",
    cols: [
      "id",
      "username",
      "first_name",
      "last_name",
      "first_name_en",
      "last_name_en",
      "father_name",
      "mail",
      "mobile1",
      "mobile2",
      "role_id",
      "organization_id",
      "c_admin_position_id",
      "active",
    ],
  },
  {
    name: "hotel",
    cols: [
      "id",
      "type",
      "name",
      "c_juridical_form_id",
      "c_hotel_group_id",
      "full_name",
      "identification",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "comment",
      "hotel_range",
      "main_contact_id",
    ],
  },
  {
    name: "hotel_contact",
    cols: ["id", "hotel_id", "name", "role", "phone", "email"],
  },
  {
    name: "hotel_bank_account",
    cols: [
      "id",
      "hotel_id",
      "bank",
      "account_number",
      "iban",
      "swift",
      "currency",
    ],
  },
  { name: "hotel_balance", cols: ["id", "hotel_id", "amount", "currency"] },
  {
    name: "hotel_price_list",
    cols: [
      "id",
      "hotel_id",
      "season_from",
      "season_to",
      "room_type",
      "price",
      "currency",
    ],
  },

  // ─── Per-vertical catalogs (must precede their referencing parents) ───────
  { name: "c_avia_group", cols: ["id", "name"] },
  { name: "c_transfer_group", cols: ["id", "name"] },
  { name: "c_consul_group", cols: ["id", "name"] },
  { name: "c_ensure_group", cols: ["id", "name"] },
  // Legacy has c_excursion_type — migrate it into the new c_excursion_group
  // table since we standardized the column name across verticals.
  {
    name: "c_excursion_group",
    cols: ["id", "name"],
    sourceTable: "c_excursion_type",
  },
  { name: "c_guide_category", cols: ["id", "name"] },
  { name: "cc2_transport_mark", cols: ["id", "name"] },
  {
    name: "cc2_transport_model",
    cols: ["id", "cc2_transport_mark_id", "name"],
  },
  { name: "c_transport_hydro", cols: ["id", "name"] },
  { name: "c_transport_color", cols: ["id", "name"] },
  { name: "c_transport_door", cols: ["id", "name"] },
  { name: "c_transport_category", cols: ["id", "name"] },

  // ─── avia ────────────────────────────────────────────────────────────────
  {
    name: "avia",
    cols: [
      "id",
      "type",
      "name",
      "c_juridical_form_id",
      "c_avia_group_id",
      "full_name",
      "identification",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "comment",
      "code",
      // main_contact_id / main_bank_account_id intentionally omitted on the
      // first pass — the rows they reference don't exist yet. Patched
      // separately after sub-entity migration if needed.
    ],
  },
  {
    name: "avia_contact",
    cols: [
      "id",
      "avia_id",
      "name",
      "company",
      "position",
      "mail",
      "address",
      "juridical_address",
      "mobile",
      "phone",
      "info",
      "main",
    ],
  },
  {
    name: "avia_bank_account",
    cols: [
      "id",
      "avia_id",
      "bank_code",
      "a_a",
      "currency",
      "bank_name",
      "swift",
      "main",
    ],
  },
  {
    name: "avia_balance",
    cols: [
      "id",
      "avia_id",
      "set_date",
      "c_pay_prescript",
      "arrears",
      "pay",
      "document_number",
      "type",
      "pay_type",
      "invoice_number",
      "p_order_id",
      "currency_id",
      "currency_name",
      "currency_cource",
    ],
  },

  // ─── transfer ────────────────────────────────────────────────────────────
  {
    name: "transfer",
    cols: [
      "id",
      "type",
      "name",
      "c_juridical_form_id",
      "c_transfer_group_id",
      "full_name",
      "identification",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "comment",
      "code",
      "text_en",
      "text_ge",
      "main_transfer_list_id",
    ],
  },
  {
    name: "transfer_contact",
    cols: [
      "id",
      "transfer_id",
      "name",
      "company",
      "position",
      "mail",
      "address",
      "juridical_address",
      "mobile",
      "phone",
      "info",
      "main",
    ],
  },
  {
    name: "transfer_bank_account",
    cols: [
      "id",
      "transfer_id",
      "bank_code",
      "a_a",
      "currency",
      "bank_name",
      "swift",
      "main",
    ],
  },
  {
    name: "transfer_balance",
    cols: [
      "id",
      "transfer_id",
      "set_date",
      "c_pay_prescript",
      "arrears",
      "pay",
      "document_number",
      "type",
      "pay_type",
      "invoice_number",
      "p_order_id",
      "currency_id",
      "currency_name",
      "currency_cource",
    ],
  },

  // ─── consul ─────────────────────────────────────────────────────────────
  {
    name: "consul",
    cols: [
      "id",
      "type",
      "name",
      "c_juridical_form_id",
      "c_consul_group_id",
      "full_name",
      "identification",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "comment",
    ],
  },
  {
    name: "consul_contact",
    cols: [
      "id",
      "consul_id",
      "name",
      "company",
      "position",
      "mail",
      "address",
      "juridical_address",
      "mobile",
      "phone",
      "info",
      "main",
    ],
  },
  {
    name: "consul_bank_account",
    cols: [
      "id",
      "consul_id",
      "bank_code",
      "a_a",
      "currency",
      "bank_name",
      "swift",
      "main",
    ],
  },
  {
    name: "consul_balance",
    cols: [
      "id",
      "consul_id",
      "set_date",
      "c_pay_prescript",
      "arrears",
      "pay",
      "document_number",
      "type",
      "pay_type",
      "invoice_number",
      "p_order_id",
      "currency_id",
      "currency_name",
      "currency_cource",
    ],
  },

  // ─── ensure (insurance) ─────────────────────────────────────────────────
  {
    name: "ensure",
    cols: [
      "id",
      "type",
      "name",
      "c_juridical_form_id",
      "c_ensure_group_id",
      "full_name",
      "identification",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "comment",
      "code",
    ],
  },
  {
    name: "ensure_contact",
    cols: [
      "id",
      "ensure_id",
      "name",
      "company",
      "position",
      "mail",
      "address",
      "juridical_address",
      "mobile",
      "phone",
      "info",
      "main",
    ],
  },
  {
    name: "ensure_bank_account",
    cols: [
      "id",
      "ensure_id",
      "bank_code",
      "a_a",
      "currency",
      "bank_name",
      "swift",
      "main",
    ],
  },
  {
    name: "ensure_balance",
    cols: [
      "id",
      "ensure_id",
      "set_date",
      "c_pay_prescript",
      "arrears",
      "pay",
      "document_number",
      "type",
      "pay_type",
      "invoice_number",
      "p_order_id",
      "currency_id",
      "currency_name",
      "currency_cource",
    ],
  },

  // ─── excursion — no legacy company table, sub-entities start empty ──────
  // (excursion + sub-entities exist as empty target tables; nothing to migrate)

  // ─── guide ──────────────────────────────────────────────────────────────
  {
    name: "guide",
    cols: [
      "id",
      "username",
      "type",
      "first_name",
      "last_name",
      "first_name_en",
      "last_name_en",
      "self_number",
      "pasport_number",
      "gender",
      "birthday",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "c_guide_category_id",
      "address",
      "phone_home",
      "phone_work",
      "phone_mobile",
      "mobile",
      "fax",
      "mail",
      "info1",
      "info2",
      "message",
      "ok_message",
      "start_date",
      "start_balance",
      "active",
    ],
  },

  // ─── transport ──────────────────────────────────────────────────────────
  {
    name: "transport",
    cols: [
      "id",
      "holder_name",
      "phone",
      "holder_contact1",
      "holder_contact2",
      "cc1_country_id",
      "cc1_region_id",
      "cc1_city_id",
      "cc2_transport_mark_id",
      "cc2_transport_model_id",
      "year",
      "c_transport_hydro_id",
      "c_transport_color_id",
      "c_transport_door_id",
      "rudder",
      "c_transport_category_id",
      "parameter1",
      "parameter2",
      "parameter3",
      "parameter4",
      "parameter5",
      "parameter6",
      "fuel_count",
      "commuter_count",
    ],
  },

  // ─── Orders + Refunds (cross-vertical) ──────────────────────────────────
  // p_order parent must precede its line-item children and tourists.
  {
    name: "p_order",
    cols: [
      "id",
      "order_number",
      "geter_invoice_number",
      "self_invoice_number",
      "avia_invoice_number",
      "additional_number",
      "c_semblance",
      "client_id",
      "client_first_name",
      "client_last_name",
      "client_pasport_number",
      "client_self_number",
      "client_phone",
      "client_category",
      "client_address",
      "company_parameters_id",
      "cm_name",
      "cm_juridical_address",
      "cm_address",
      "cm_identification",
      "cm_director",
      "cm_bank_name",
      "cm_bank_code",
      "cm_bank_number",
      "cm_currency",
      "order_date",
      "level",
      "c_pay_type",
      "c_pay_proviso",
      "all_sell_price",
      "creator_user_id",
      "create_date",
      "create_time",
      "days",
      "client_country",
      "client_region",
      "client_city",
      "in_pay",
      "client_birthday",
      "get_course_date",
      "info",
    ],
  },
  {
    name: "p_order_tourist",
    cols: [
      "id",
      "p_order_id",
      "client_id",
      "username",
      "first_name",
      "last_name",
      "first_name_en",
      "last_name_en",
      "gender",
      "birthday",
      "mobile",
      "mail",
      "type",
      "cc1_country",
      "cc1_region",
      "cc1_city",
      "self_number",
      "pasport_number",
    ],
  },
  {
    name: "p_order_hotel",
    cols: [
      "id",
      "p_order_id",
      "hotel_id",
      "hotel_name",
      "hotel_full_name",
      "hotel_juridical_form",
      "hotel_group",
      "hotel_identification",
      "hotel_mail",
      "hotel_phone",
      "hotel_mobile",
      "hotel_city",
      "hotel_country",
      "hotel_region",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_city",
      "company_country",
      "company_region",
      "c_number_category",
      "cc_room_type",
      "check_in",
      "check_out",
      "check_in_time",
      "check_out_time",
      "days",
      "room_price",
      "currency_id",
      "currency_name",
      "currency_cource",
      "percent",
      "sell_price",
      "child1_age",
      "child2_age",
      "c_board_type",
      "drg",
      "owner_user_id",
      "comission_percent",
      "sale_percent",
      "drg_price",
      "get_course_date",
    ],
  },
  {
    name: "p_order_avia",
    cols: [
      "id",
      "p_order_id",
      "avia_id",
      "avia_name",
      "avia_full_name",
      "avia_juridical_form",
      "avia_group",
      "avia_identification",
      "avia_mail",
      "avia_phone",
      "avia_mobile",
      "avia_code",
      "avia_country",
      "avia_region",
      "avia_city",
      "p_order_tourist_id",
      "company_id",
      "company_name",
      "company_full_name",
      "company_country",
      "company_region",
      "company_city",
      "c_avia_ticket_type",
      "ticket_number",
      "c_avia_direction",
      "issue_date",
      "fly_date",
      "tarif_code",
      "tarif",
      "a_p_taqsa1",
      "a_p_taqsa2",
      "a_p_taqsa3",
      "a_p_taqsa4",
      "other",
      "service_fee",
      "corporation_client_comission",
      "ticket_price",
      "c_bron_class",
      "drg",
      "owner_user_id",
      "percent",
      "company_id1",
      "company_name1",
      "company_full_name1",
      "company_country1",
      "company_region1",
      "company_city1",
      "drg_price",
      "get_course_date",
      "unfly_date",
    ],
  },
  {
    name: "p_order_transfer",
    cols: [
      "id",
      "p_order_id",
      "transfer_id",
      "transfer_name",
      "transfer_full_name",
      "transfer_juridical_form",
      "transfer_group",
      "transfer_identification",
      "transfer_mail",
      "transfer_phone",
      "transfer_mobile",
      "transfer_city",
      "transfer_country",
      "transfer_region",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_city",
      "company_country",
      "company_region",
      "c_transfer_type",
      "c_transfer_direction",
      "invoice_number",
      "comment",
      "price",
      "currency_id",
      "currency_name",
      "currency_cource",
      "percent",
      "sell_price",
      "human_count",
      "age",
      "issue_date",
      "drg",
      "owner_user_id",
      "sale_percent",
      "comission_percent",
      "drg_price",
      "get_course_date",
    ],
  },
  {
    name: "p_order_excursion",
    cols: [
      "id",
      "p_order_id",
      "pay_name",
      "price",
      "currency_id",
      "currency_name",
      "currency_cource",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_country",
      "company_region",
      "company_city",
      "c_excursion_type",
      "count",
      "sell_price",
      "start_date",
      "end_date",
      "drg",
      "owner_user_id",
      "guide_id",
      "guide_first_name",
      "guide_last_name",
      "guide_pasport",
      "guide_self_number",
      "guide_phone",
      "guide_category",
      "guide_address",
      "guide_birthday",
      "guide_country",
      "guide_region",
      "guide_city",
      "transport_id",
      "transport_mark",
      "transport_model",
      "transport_holder_name",
      "transport_holder_phone",
      "sale_percent",
      "company_price",
      "guide_price",
      "transport_price",
      "drg_price",
      "get_course_date",
    ],
  },
  {
    name: "p_order_ensure",
    cols: [
      "id",
      "p_order_id",
      "ensure_id",
      "ensure_name",
      "ensure_full_name",
      "ensure_juridical_form",
      "ensure_group",
      "ensure_identification",
      "ensure_mail",
      "ensure_phone",
      "ensure_mobile",
      "ensure_country",
      "ensure_region",
      "ensure_city",
      "p_order_tourist_id",
      "c_ensure_type",
      "from_date",
      "to_date",
      "day_count",
      "ensure_limit",
      "currency_id",
      "currency_name",
      "currency_cource",
      "bonus",
      "currency_id1",
      "currency_name1",
      "currency_cource1",
      "percent",
      "franshiza",
      "currency_id2",
      "currency_name2",
      "currency_cource2",
      "issue_date",
      "issue_place",
      "invoice_number",
      "polise_number",
      "comment",
      "drg",
      "owner_user_id",
      "sale_percent",
      "drg_price",
      "get_course_date",
    ],
  },
  {
    name: "p_order_visa",
    cols: [
      "id",
      "p_order_id",
      "pay_name",
      "price",
      "currency_id",
      "currency_name",
      "currency_cource",
      "consul_id",
      "consul_name",
      "consul_full_name",
      "consul_juridical_form",
      "consul_group",
      "consul_identification",
      "consul_mail",
      "consul_phone",
      "consul_mobile",
      "consul_country",
      "consul_region",
      "consul_city",
      "invoice_number",
      "ensure_number",
      "sell_price",
      "start_date",
      "end_date",
      "free",
      "p_order_tourist_id",
      "issue_date",
      "drg",
      "owner_user_id",
      "sale_percent",
      "drg_price",
      "get_course_date",
    ],
  },
  {
    name: "p_order_service",
    cols: [
      "id",
      "p_order_id",
      "pay_name",
      "price",
      "currency_id",
      "currency_name",
      "currency_cource",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "c_service_type",
      "count",
      "sell_price",
      "start_date",
      "end_date",
      "company_country",
      "company_region",
      "company_city",
      "drg",
      "owner_user_id",
      "sale_percent",
      "drg_price",
      "get_course_date",
    ],
  },

  // p_refund parent + line items
  {
    name: "p_refund",
    cols: [
      "id",
      "order_number",
      "geter_invoice_number",
      "self_invoice_number",
      "avia_invoice_number",
      "additional_number",
      "c_semblance",
      "client_id",
      "client_first_name",
      "client_last_name",
      "client_pasport_number",
      "client_self_number",
      "client_phone",
      "client_category",
      "client_address",
      "company_parameters_id",
      "cm_name",
      "cm_juridical_address",
      "cm_address",
      "cm_identification",
      "cm_director",
      "cm_bank_name",
      "cm_bank_code",
      "cm_bank_number",
      "cm_currency",
      "order_date",
      "level",
      "c_pay_type",
      "c_pay_proviso",
      "all_sell_price",
      "creator_user_id",
      "create_date",
      "create_time",
      "days",
      "client_country",
      "client_region",
      "client_city",
      "in_pay",
      "client_birthday",
      "get_course_date",
      "info",
      "p_order_id",
    ],
  },
  {
    name: "p_refund_tourist",
    cols: [
      "id",
      "p_refund_id",
      "client_id",
      "username",
      "first_name",
      "last_name",
      "first_name_en",
      "last_name_en",
      "gender",
      "birthday",
      "mobile",
      "mail",
      "type",
      "cc1_country",
      "cc1_region",
      "cc1_city",
      "self_number",
      "pasport_number",
    ],
  },
  {
    name: "p_refund_hotel",
    cols: [
      "id",
      "p_refund_id",
      "hotel_id",
      "hotel_name",
      "hotel_full_name",
      "hotel_juridical_form",
      "hotel_group",
      "hotel_identification",
      "hotel_mail",
      "hotel_phone",
      "hotel_mobile",
      "hotel_country",
      "hotel_region",
      "hotel_city",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_country",
      "company_region",
      "company_city",
      "c_number_category",
      "cc_room_type",
      "check_in",
      "check_out",
      "check_in_time",
      "check_out_time",
      "days",
      "child1_age",
      "child2_age",
      "uncharge",
      "currency_id",
      "currency_name",
      "currency_cource",
      "client_uncharge",
      "c_board_type",
      "drg",
      "owner_user_id",
      "get_course_date",
    ],
  },
  {
    name: "p_refund_avia",
    cols: [
      "id",
      "p_refund_id",
      "avia_id",
      "avia_name",
      "avia_full_name",
      "avia_juridical_form",
      "avia_group",
      "avia_identification",
      "avia_mail",
      "avia_phone",
      "avia_mobile",
      "avia_code",
      "avia_country",
      "avia_region",
      "avia_city",
      "p_refund_tourist_id",
      "company_id",
      "company_name",
      "company_full_name",
      "company_country",
      "company_region",
      "company_city",
      "c_avia_ticket_type",
      "ticket_number",
      "c_avia_direction",
      "issue_date",
      "fly_date",
      "tarif_code",
      "c_bron_class",
      "uncharge",
      "subagent_uncharge",
      "client_uncharge",
      "drg",
      "owner_user_id",
      "company_id1",
      "company_name1",
      "company_full_name1",
      "company_country1",
      "company_region1",
      "company_city1",
      "get_course_date",
      "unfly_date",
    ],
  },
  {
    name: "p_refund_transfer",
    cols: [
      "id",
      "p_refund_id",
      "transfer_id",
      "transfer_name",
      "transfer_full_name",
      "transfer_juridical_form",
      "transfer_group",
      "transfer_identification",
      "transfer_mail",
      "transfer_phone",
      "transfer_mobile",
      "transfer_country",
      "transfer_region",
      "transfer_city",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_country",
      "company_region",
      "company_city",
      "c_transfer_type",
      "c_transfer_direction",
      "human_count",
      "uncharge",
      "currency_id",
      "currency_name",
      "currency_cource",
      "client_uncharge",
      "invoice_number",
      "comment",
      "issue_date",
      "drg",
      "owner_user_id",
      "get_course_date",
    ],
  },
  {
    name: "p_refund_excursion",
    cols: [
      "id",
      "p_refund_id",
      "pay_name",
      "uncharge",
      "currency_id",
      "currency_name",
      "currency_cource",
      "guide_uncharge",
      "currency_id1",
      "currency_name1",
      "currency_cource1",
      "transport_uncharge",
      "currency_id2",
      "currency_name2",
      "currency_cource2",
      "client_uncharge",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_country",
      "company_region",
      "company_city",
      "c_excursion_type",
      "count",
      "start_date",
      "end_date",
      "drg",
      "owner_user_id",
      "guide_id",
      "guide_first_name",
      "guide_last_name",
      "guide_pasport",
      "guide_self_number",
      "guide_phone",
      "guide_category",
      "guide_address",
      "guide_birthday",
      "guide_country",
      "guide_region",
      "guide_city",
      "transport_id",
      "transport_mark",
      "transport_model",
      "transport_holder_name",
      "transport_holder_phone",
      "get_course_date",
    ],
  },
  {
    name: "p_refund_ensure",
    cols: [
      "id",
      "p_refund_id",
      "ensure_id",
      "ensure_name",
      "ensure_full_name",
      "ensure_juridical_form",
      "ensure_group",
      "ensure_identification",
      "ensure_mail",
      "ensure_phone",
      "ensure_mobile",
      "ensure_country",
      "ensure_region",
      "ensure_city",
      "p_refund_tourist_id",
      "c_ensure_type",
      "from_date",
      "to_date",
      "day_count",
      "ensure_limit",
      "currency_id",
      "currency_name",
      "currency_cource",
      "uncharge",
      "currency_id1",
      "currency_name1",
      "currency_cource1",
      "client_uncharge",
      "franshiza",
      "currency_id2",
      "currency_name2",
      "currency_cource2",
      "issue_date",
      "issue_place",
      "invoice_number",
      "polise_number",
      "comment",
      "drg",
      "owner_user_id",
      "get_course_date",
    ],
  },
  {
    name: "p_refund_visa",
    cols: [
      "id",
      "p_refund_id",
      "pay_name",
      "uncharge",
      "currency_id",
      "currency_name",
      "currency_cource",
      "client_uncharge",
      "consul_id",
      "consul_name",
      "consul_full_name",
      "consul_juridical_form",
      "consul_group",
      "consul_identification",
      "consul_mail",
      "consul_phone",
      "consul_mobile",
      "consul_country",
      "consul_region",
      "consul_city",
      "invoice_number",
      "start_date",
      "end_date",
      "p_refund_tourist_id",
      "issue_date",
      "drg",
      "owner_user_id",
      "get_course_date",
    ],
  },
  {
    name: "p_refund_service",
    cols: [
      "id",
      "p_refund_id",
      "pay_name",
      "uncharge",
      "currency_id",
      "currency_name",
      "currency_cource",
      "client_uncharge",
      "company_id",
      "company_name",
      "company_full_name",
      "company_juridical_form",
      "company_group",
      "company_identification",
      "company_mail",
      "company_phone",
      "company_mobile",
      "company_country",
      "company_region",
      "company_city",
      "c_service_type",
      "start_date",
      "end_date",
      "drg",
      "owner_user_id",
      "get_course_date",
      "count",
    ],
  },
];

// FK columns that legacy mariadb stored as 0 instead of NULL. Coerced post-insert.
const FK_ZERO_TO_NULL: Record<string, string[]> = {
  avia: [
    "c_juridical_form_id",
    "c_avia_group_id",
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
  ],
  transfer: [
    "c_juridical_form_id",
    "c_transfer_group_id",
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
  ],
  consul: [
    "c_juridical_form_id",
    "c_consul_group_id",
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
  ],
  ensure: [
    "c_juridical_form_id",
    "c_ensure_group_id",
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
  ],
  excursion: [
    "c_juridical_form_id",
    "c_excursion_group_id",
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
  ],
  guide: [
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
    "c_guide_category_id",
  ],
  transport: [
    "cc1_country_id",
    "cc1_region_id",
    "cc1_city_id",
    "cc2_transport_mark_id",
    "cc2_transport_model_id",
    "c_transport_hydro_id",
    "c_transport_color_id",
    "c_transport_door_id",
    "c_transport_category_id",
  ],
  p_order: ["client_id"],
  p_order_tourist: ["p_order_id", "client_id"],
  p_order_hotel: ["p_order_id", "hotel_id"],
  p_order_avia: ["p_order_id", "avia_id", "p_order_tourist_id"],
  p_order_transfer: ["p_order_id", "transfer_id"],
  p_order_excursion: ["p_order_id", "company_id", "guide_id", "transport_id"],
  p_order_ensure: ["p_order_id", "ensure_id", "p_order_tourist_id"],
  p_order_visa: ["p_order_id", "consul_id", "p_order_tourist_id"],
  p_order_service: ["p_order_id"],
  p_refund: ["client_id", "p_order_id"],
  p_refund_tourist: ["p_refund_id", "client_id"],
  p_refund_hotel: ["p_refund_id", "hotel_id"],
  p_refund_avia: ["p_refund_id", "avia_id", "p_refund_tourist_id"],
  p_refund_transfer: ["p_refund_id", "transfer_id"],
  p_refund_excursion: ["p_refund_id", "company_id", "guide_id", "transport_id"],
  p_refund_ensure: ["p_refund_id", "ensure_id", "p_refund_tourist_id"],
  p_refund_visa: ["p_refund_id", "consul_id", "p_refund_tourist_id"],
  p_refund_service: ["p_refund_id"],
};

async function main() {
  const maria = await mysql.createConnection({ uri: MARIA_URL });
  const pg = new PgClient({
    connectionString: SUPABASE_DB_URL,
    ssl: { rejectUnauthorized: false },
  });
  await pg.connect();
  console.log("connected");

  await pg.query("set session_replication_role = replica"); // bypass FK during bulk insert
  try {
    for (const t of TABLES as Array<{
      name: string;
      cols: string[];
      sourceTable?: string;
    }>) {
      const sourceTable = t.sourceTable ?? t.name;
      // Best-effort: select only columns that exist in source
      const [legacyCols] = await maria.query<mysql.RowDataPacket[]>(
        `select COLUMN_NAME from information_schema.columns where table_schema=database() and table_name=?`,
        [sourceTable],
      );
      const availableCols = new Set(legacyCols.map((r) => r.COLUMN_NAME));
      const cols = t.cols.filter((c) => availableCols.has(c));
      if (cols.length === 0) {
        console.warn(
          `skip ${t.name} — no columns matched (source ${sourceTable})`,
        );
        continue;
      }

      const [rows] = await maria.query<mysql.RowDataPacket[]>(
        `select ${cols.map((c) => `\`${c}\``).join(",")} from \`${sourceTable}\``,
      );

      // NOTE: `truncate ... cascade` follows FK relationships even when
      // `session_replication_role = replica` is set — replica only disables
      // *triggers*, not FK-graph DDL behavior. Some verticals (avia, transfer,
      // …) have a parent⇄child cycle (e.g. avia ↔ avia_contact via
      // main_contact_id), so truncating any one cascade-wipes the whole graph.
      // Use a plain `delete` instead and reset the identity sequence manually.
      await pg.query(`delete from ${t.name}`);
      await pg.query(
        `select setval(pg_get_serial_sequence('${t.name}', 'id'), 1, false)`,
      );
      if (rows.length === 0) {
        console.log(`${t.name}: 0 rows`);
        continue;
      }

      // Postgres caps parameters at 65535 per query. Chunk rows so chunk * cols
      // stays well under that.
      const maxParamsPerQuery = 60000;
      const chunkSize = Math.max(
        1,
        Math.floor(maxParamsPerQuery / cols.length),
      );
      for (let off = 0; off < rows.length; off += chunkSize) {
        const slice = rows.slice(off, off + chunkSize);
        const placeholders = slice
          .map(
            (_, i) =>
              `(${cols.map((__, j) => `$${i * cols.length + j + 1}`).join(",")})`,
          )
          .join(",");
        const values = slice.flatMap((r) =>
          cols.map((c) => {
            const v = r[c];
            if (v === undefined || v === null) return null;
            if (v instanceof Date) return v.toISOString();
            return v;
          }),
        );
        await pg.query(
          `insert into ${t.name} (${cols.join(",")}) values ${placeholders}`,
          values,
        );
      }

      // Restart sequence past the highest id we just inserted
      const maxId = rows.reduce(
        (m: number, r: any) => Math.max(m, Number(r.id) || 0),
        0,
      );
      if (maxId > 0) {
        await pg.query(
          `select setval(pg_get_serial_sequence('${t.name}', 'id'), $1, true)`,
          [maxId],
        );
      }

      console.log(`${t.name}: ${rows.length} rows`);
    }

    // ─── Post-migration cleanup: coerce 0 sentinels to NULL on FK columns ───
    // Legacy mariadb stored unselected FKs as 0; Postgres rejects those at FK
    // check time (and they'd point at non-existent parents anyway).
    for (const [table, fkCols] of Object.entries(FK_ZERO_TO_NULL)) {
      for (const col of fkCols) {
        await pg.query(`update ${table} set ${col} = null where ${col} = 0`);
      }
    }
    console.log("FK-zero coercion done");
  } finally {
    await pg.query("set session_replication_role = default");
    await pg.end();
    await maria.end();
    console.log("done");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
