-- 0003_orders_refunds.sql
-- Cross-vertical order + refund workflow. Mirrors legacy p_order, p_order_<v>,
-- p_order_tourist, p_refund, p_refund_<v> from travelpl_tm.sql verbatim so the
-- legacy domain knowledge keeps lining up with code.
--
-- Each per-vertical line item table FKs to its parent (`p_order` or `p_refund`)
-- and to the catalog row (`hotel_id`, `avia_id`, …) — with the rest of the
-- column set kept as denormalized text so historical orders survive catalog
-- edits (legacy behavior).

set check_function_bodies = false;

-- ============================================================================
-- p_order (parent) + per-vertical line items + p_order_tourist
-- ============================================================================

create table if not exists p_order (
  id bigserial primary key,
  order_number bigint,
  geter_invoice_number text,
  self_invoice_number text,
  avia_invoice_number text,
  additional_number text,
  c_semblance text,             -- status
  client_id bigint references administration(id),
  client_first_name text,
  client_last_name text,
  client_pasport_number text,
  client_self_number text,
  client_phone text,
  client_category text,
  client_address text,
  company_parameters_id bigint,
  cm_name text,
  cm_juridical_address text,
  cm_address text,
  cm_identification text,
  cm_director text,
  cm_bank_name text,
  cm_bank_code text,
  cm_bank_number text,
  cm_currency text,
  order_date date,
  level smallint,
  c_pay_type text,
  c_pay_proviso text,
  all_sell_price numeric(14,2),
  creator_user_id bigint,
  create_date date,
  create_time time,
  days bigint,
  client_country text,
  client_region text,
  client_city text,
  in_pay boolean,
  client_birthday date,
  get_course_date date,
  info text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_tourist (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  client_id bigint references administration(id),
  username text,
  first_name text,
  last_name text,
  first_name_en text,
  last_name_en text,
  gender smallint,
  birthday date,
  mobile text,
  mail text,
  type smallint,
  cc1_country text,
  cc1_region text,
  cc1_city text,
  self_number text,
  pasport_number text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_hotel (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  hotel_id bigint references hotel(id),
  hotel_name text,
  hotel_full_name text,
  hotel_juridical_form text,
  hotel_group text,
  hotel_identification text,
  hotel_mail text,
  hotel_phone text,
  hotel_mobile text,
  hotel_city text,
  hotel_country text,
  hotel_region text,
  company_id bigint,
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_city text,
  company_country text,
  company_region text,
  c_number_category text,
  cc_room_type text,
  check_in date,
  check_out date,
  check_in_time time,
  check_out_time time,
  days bigint,
  room_price numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  percent numeric(10,4),
  sell_price numeric(14,2),
  child1_age bigint,
  child2_age bigint,
  c_board_type text,
  drg smallint,
  owner_user_id bigint,
  comission_percent numeric(10,4),
  sale_percent numeric(10,4),
  drg_price numeric(14,2),
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_avia (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  avia_id bigint references avia(id),
  avia_name text,
  avia_full_name text,
  avia_juridical_form text,
  avia_group text,
  avia_identification text,
  avia_mail text,
  avia_phone text,
  avia_mobile text,
  avia_code text,
  avia_country text,
  avia_region text,
  avia_city text,
  p_order_tourist_id bigint references p_order_tourist(id) on delete set null,
  company_id bigint,
  company_name text,
  company_full_name text,
  company_country text,
  company_region text,
  company_city text,
  c_avia_ticket_type text,
  ticket_number text,
  c_avia_direction text,
  issue_date date,
  fly_date date,
  tarif_code text,
  tarif numeric(14,2),
  a_p_taqsa1 numeric(14,2),
  a_p_taqsa2 numeric(14,2),
  a_p_taqsa3 numeric(14,2),
  a_p_taqsa4 numeric(14,2),
  other numeric(14,2),
  service_fee numeric(14,2),
  corporation_client_comission numeric(14,2),
  ticket_price numeric(14,2),
  c_bron_class text,
  drg smallint,
  owner_user_id bigint,
  percent numeric(10,4),
  company_id1 bigint,
  company_name1 text,
  company_full_name1 text,
  company_country1 text,
  company_region1 text,
  company_city1 text,
  drg_price numeric(14,2),
  get_course_date date,
  unfly_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_transfer (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  transfer_id bigint references transfer(id),
  transfer_name text,
  transfer_full_name text,
  transfer_juridical_form text,
  transfer_group text,
  transfer_identification text,
  transfer_mail text,
  transfer_phone text,
  transfer_mobile text,
  transfer_city text,
  transfer_country text,
  transfer_region text,
  company_id bigint,
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_city text,
  company_country text,
  company_region text,
  c_transfer_type text,
  c_transfer_direction text,
  invoice_number text,
  comment text,
  price numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  percent numeric(10,4),
  sell_price numeric(14,2),
  human_count bigint,
  age bigint,
  issue_date date,
  drg smallint,
  owner_user_id bigint,
  sale_percent numeric(10,4),
  comission_percent numeric(10,4),
  drg_price numeric(14,2),
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_excursion (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  pay_name text,
  price numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  company_id bigint references excursion(id),
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_country text,
  company_region text,
  company_city text,
  c_excursion_type text,
  count bigint,
  sell_price numeric(14,2),
  start_date date,
  end_date date,
  drg smallint,
  owner_user_id bigint,
  guide_id bigint references guide(id),
  guide_first_name text,
  guide_last_name text,
  guide_pasport text,
  guide_self_number text,
  guide_phone text,
  guide_category text,
  guide_address text,
  guide_birthday text,
  guide_country text,
  guide_region text,
  guide_city text,
  transport_id bigint references transport(id),
  transport_mark text,
  transport_model text,
  transport_holder_name text,
  transport_holder_phone text,
  sale_percent numeric(10,4),
  company_price numeric(14,2),
  guide_price numeric(14,2),
  transport_price numeric(14,2),
  drg_price numeric(14,2),
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_ensure (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  ensure_id bigint references ensure(id),
  ensure_name text,
  ensure_full_name text,
  ensure_juridical_form text,
  ensure_group text,
  ensure_identification text,
  ensure_mail text,
  ensure_phone text,
  ensure_mobile text,
  ensure_country text,
  ensure_region text,
  ensure_city text,
  p_order_tourist_id bigint references p_order_tourist(id) on delete set null,
  c_ensure_type text,
  from_date date,
  to_date date,
  day_count bigint,
  ensure_limit numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  bonus numeric(14,2),
  currency_id1 bigint,
  currency_name1 text,
  currency_cource1 numeric(14,4),
  percent bigint,
  franshiza numeric(14,2),
  currency_id2 bigint,
  currency_name2 text,
  currency_cource2 numeric(14,4),
  issue_date date,
  issue_place text,
  invoice_number text,
  polise_number text,
  comment text,
  drg smallint,
  owner_user_id bigint,
  sale_percent numeric(10,4),
  drg_price numeric(14,2),
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_visa (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  pay_name text,
  price numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  consul_id bigint references consul(id),
  consul_name text,
  consul_full_name text,
  consul_juridical_form text,
  consul_group text,
  consul_identification text,
  consul_mail text,
  consul_phone text,
  consul_mobile text,
  consul_country text,
  consul_region text,
  consul_city text,
  invoice_number text,
  ensure_number text,
  sell_price numeric(14,2),
  start_date date,
  end_date date,
  free numeric(14,2),
  p_order_tourist_id bigint references p_order_tourist(id) on delete set null,
  issue_date date,
  drg smallint,
  owner_user_id bigint,
  sale_percent numeric(10,4),
  drg_price numeric(14,2),
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_order_service (
  id bigserial primary key,
  p_order_id bigint references p_order(id) on delete cascade,
  pay_name text,
  price numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  company_id bigint,
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  c_service_type text,
  count bigint,
  sell_price numeric(14,2),
  start_date date,
  end_date date,
  company_country text,
  company_region text,
  company_city text,
  drg smallint,
  owner_user_id bigint,
  sale_percent numeric(10,4),
  drg_price numeric(14,2),
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================================
-- p_refund (mirror of p_order) + per-vertical refunds + p_refund_tourist
-- ============================================================================

create table if not exists p_refund (
  id bigserial primary key,
  order_number bigint,
  geter_invoice_number text,
  self_invoice_number text,
  avia_invoice_number text,
  additional_number text,
  c_semblance text,
  client_id bigint references administration(id),
  client_first_name text,
  client_last_name text,
  client_pasport_number text,
  client_self_number text,
  client_phone text,
  client_category text,
  client_address text,
  company_parameters_id bigint,
  cm_name text,
  cm_juridical_address text,
  cm_address text,
  cm_identification text,
  cm_director text,
  cm_bank_name text,
  cm_bank_code text,
  cm_bank_number text,
  cm_currency text,
  order_date date,
  level smallint,
  c_pay_type text,
  c_pay_proviso text,
  all_sell_price numeric(14,2),
  creator_user_id bigint,
  create_date date,
  create_time time,
  days bigint,
  client_country text,
  client_region text,
  client_city text,
  in_pay boolean,
  client_birthday date,
  get_course_date date,
  info text,
  p_order_id bigint references p_order(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_tourist (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  client_id bigint references administration(id),
  username text,
  first_name text,
  last_name text,
  first_name_en text,
  last_name_en text,
  gender smallint,
  birthday date,
  mobile text,
  mail text,
  type smallint,
  cc1_country text,
  cc1_region text,
  cc1_city text,
  self_number text,
  pasport_number text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_hotel (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  hotel_id bigint references hotel(id),
  hotel_name text,
  hotel_full_name text,
  hotel_juridical_form text,
  hotel_group text,
  hotel_identification text,
  hotel_mail text,
  hotel_phone text,
  hotel_mobile text,
  hotel_country text,
  hotel_region text,
  hotel_city text,
  company_id bigint,
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_country text,
  company_region text,
  company_city text,
  c_number_category text,
  cc_room_type text,
  check_in date,
  check_out date,
  check_in_time time,
  check_out_time time,
  days bigint,
  child1_age bigint,
  child2_age bigint,
  uncharge numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  client_uncharge numeric(14,2),
  c_board_type text,
  drg smallint,
  owner_user_id bigint,
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_avia (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  avia_id bigint references avia(id),
  avia_name text,
  avia_full_name text,
  avia_juridical_form text,
  avia_group text,
  avia_identification text,
  avia_mail text,
  avia_phone text,
  avia_mobile text,
  avia_code text,
  avia_country text,
  avia_region text,
  avia_city text,
  p_refund_tourist_id bigint references p_refund_tourist(id) on delete set null,
  company_id bigint,
  company_name text,
  company_full_name text,
  company_country text,
  company_region text,
  company_city text,
  c_avia_ticket_type text,
  ticket_number text,
  c_avia_direction text,
  issue_date date,
  fly_date date,
  tarif_code text,
  c_bron_class text,
  uncharge numeric(14,2),
  subagent_uncharge numeric(14,2),
  client_uncharge numeric(14,2),
  drg smallint,
  owner_user_id bigint,
  company_id1 bigint,
  company_name1 text,
  company_full_name1 text,
  company_country1 text,
  company_region1 text,
  company_city1 text,
  get_course_date date,
  unfly_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_transfer (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  transfer_id bigint references transfer(id),
  transfer_name text,
  transfer_full_name text,
  transfer_juridical_form text,
  transfer_group text,
  transfer_identification text,
  transfer_mail text,
  transfer_phone text,
  transfer_mobile text,
  transfer_country text,
  transfer_region text,
  transfer_city text,
  company_id bigint,
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_country text,
  company_region text,
  company_city text,
  c_transfer_type text,
  c_transfer_direction text,
  human_count bigint,
  uncharge numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  client_uncharge numeric(14,2),
  invoice_number text,
  comment text,
  issue_date date,
  drg smallint,
  owner_user_id bigint,
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_excursion (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  pay_name text,
  uncharge numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  guide_uncharge numeric(14,2),
  currency_id1 bigint,
  currency_name1 text,
  currency_cource1 numeric(14,4),
  transport_uncharge numeric(14,2),
  currency_id2 bigint,
  currency_name2 text,
  currency_cource2 numeric(14,4),
  client_uncharge numeric(14,2),
  company_id bigint references excursion(id),
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_country text,
  company_region text,
  company_city text,
  c_excursion_type text,
  count bigint,
  start_date date,
  end_date date,
  drg smallint,
  owner_user_id bigint,
  guide_id bigint references guide(id),
  guide_first_name text,
  guide_last_name text,
  guide_pasport text,
  guide_self_number text,
  guide_phone text,
  guide_category text,
  guide_address text,
  guide_birthday text,
  guide_country text,
  guide_region text,
  guide_city text,
  transport_id bigint references transport(id),
  transport_mark text,
  transport_model text,
  transport_holder_name text,
  transport_holder_phone text,
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_ensure (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  ensure_id bigint references ensure(id),
  ensure_name text,
  ensure_full_name text,
  ensure_juridical_form text,
  ensure_group text,
  ensure_identification text,
  ensure_mail text,
  ensure_phone text,
  ensure_mobile text,
  ensure_country text,
  ensure_region text,
  ensure_city text,
  p_refund_tourist_id bigint references p_refund_tourist(id) on delete set null,
  c_ensure_type text,
  from_date date,
  to_date date,
  day_count bigint,
  ensure_limit numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  uncharge numeric(14,2),
  currency_id1 bigint,
  currency_name1 text,
  currency_cource1 numeric(14,4),
  client_uncharge numeric(14,2),
  franshiza numeric(14,2),
  currency_id2 bigint,
  currency_name2 text,
  currency_cource2 numeric(14,4),
  issue_date date,
  issue_place text,
  invoice_number text,
  polise_number text,
  comment text,
  drg smallint,
  owner_user_id bigint,
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_visa (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  pay_name text,
  uncharge numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  client_uncharge numeric(14,2),
  consul_id bigint references consul(id),
  consul_name text,
  consul_full_name text,
  consul_juridical_form text,
  consul_group text,
  consul_identification text,
  consul_mail text,
  consul_phone text,
  consul_mobile text,
  consul_country text,
  consul_region text,
  consul_city text,
  invoice_number text,
  start_date date,
  end_date date,
  p_refund_tourist_id bigint references p_refund_tourist(id) on delete set null,
  issue_date date,
  drg smallint,
  owner_user_id bigint,
  get_course_date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists p_refund_service (
  id bigserial primary key,
  p_refund_id bigint references p_refund(id) on delete cascade,
  pay_name text,
  uncharge numeric(14,2),
  currency_id bigint,
  currency_name text,
  currency_cource numeric(14,4),
  client_uncharge numeric(14,2),
  company_id bigint,
  company_name text,
  company_full_name text,
  company_juridical_form text,
  company_group text,
  company_identification text,
  company_mail text,
  company_phone text,
  company_mobile text,
  company_country text,
  company_region text,
  company_city text,
  c_service_type text,
  start_date date,
  end_date date,
  drg smallint,
  owner_user_id bigint,
  get_course_date date,
  count bigint,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================================
-- Indexes — hot lookup paths
-- ============================================================================

create index if not exists p_order_client_idx on p_order(client_id);
create index if not exists p_order_order_number_idx on p_order(order_number);
create index if not exists p_order_status_idx on p_order(c_semblance);
create index if not exists p_order_order_date_idx on p_order(order_date);

create index if not exists p_order_hotel_parent_idx on p_order_hotel(p_order_id);
create index if not exists p_order_hotel_hotel_idx on p_order_hotel(hotel_id);
create index if not exists p_order_avia_parent_idx on p_order_avia(p_order_id);
create index if not exists p_order_avia_avia_idx on p_order_avia(avia_id);
create index if not exists p_order_transfer_parent_idx on p_order_transfer(p_order_id);
create index if not exists p_order_transfer_transfer_idx on p_order_transfer(transfer_id);
create index if not exists p_order_excursion_parent_idx on p_order_excursion(p_order_id);
create index if not exists p_order_excursion_company_idx on p_order_excursion(company_id);
create index if not exists p_order_ensure_parent_idx on p_order_ensure(p_order_id);
create index if not exists p_order_ensure_ensure_idx on p_order_ensure(ensure_id);
create index if not exists p_order_visa_parent_idx on p_order_visa(p_order_id);
create index if not exists p_order_visa_consul_idx on p_order_visa(consul_id);
create index if not exists p_order_service_parent_idx on p_order_service(p_order_id);
create index if not exists p_order_tourist_parent_idx on p_order_tourist(p_order_id);

create index if not exists p_refund_client_idx on p_refund(client_id);
create index if not exists p_refund_order_idx on p_refund(p_order_id);
create index if not exists p_refund_status_idx on p_refund(c_semblance);
create index if not exists p_refund_order_date_idx on p_refund(order_date);

create index if not exists p_refund_hotel_parent_idx on p_refund_hotel(p_refund_id);
create index if not exists p_refund_avia_parent_idx on p_refund_avia(p_refund_id);
create index if not exists p_refund_transfer_parent_idx on p_refund_transfer(p_refund_id);
create index if not exists p_refund_excursion_parent_idx on p_refund_excursion(p_refund_id);
create index if not exists p_refund_ensure_parent_idx on p_refund_ensure(p_refund_id);
create index if not exists p_refund_visa_parent_idx on p_refund_visa(p_refund_id);
create index if not exists p_refund_service_parent_idx on p_refund_service(p_refund_id);
create index if not exists p_refund_tourist_parent_idx on p_refund_tourist(p_refund_id);

-- ============================================================================
-- updated_at triggers — reuse set_updated_at() from 0001
-- ============================================================================

do $$
declare t text;
begin
  for t in select unnest(array[
    'p_order','p_order_tourist',
    'p_order_hotel','p_order_avia','p_order_transfer',
    'p_order_excursion','p_order_ensure','p_order_visa','p_order_service',
    'p_refund','p_refund_tourist',
    'p_refund_hotel','p_refund_avia','p_refund_transfer',
    'p_refund_excursion','p_refund_ensure','p_refund_visa','p_refund_service'
  ]) loop
    if not exists (
      select 1 from pg_trigger
      where tgname = format('%I_set_updated_at', t)::text
        and tgrelid = t::regclass
    ) then
      execute format(
        'create trigger %I_set_updated_at before update on %I for each row execute function set_updated_at();',
        t, t
      );
    end if;
  end loop;
end $$;
